# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Javascript-30
description: >- # this means to ignore newlines until "baseurl:"
  In this site I collect what I'm doing from the Javascript-30 challenge.
baseurl: "js-30" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://v-natalia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: v-natalia



# Build settings
markdown: kramdown
collections_dir: my_collections
plugins:
  - jekyll-feed

collections:
  days:
    day:
    output: true

defaults:
- scope:
      path: ""
      type: "posts"
  values:
      layout: "post"
- scope:
      path: ""
      type: "days"
  values:
      layout: "post"

defaults:
  - scope:
      path: '/assets/images'
    values:
      image: true

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: /assets/_sass
  style: compressed


images: '/assets/images'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
